# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'cafe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for cafe
  pod 'GoogleSignIn'
  pod 'GoogleMaps', '9.0.0'



  target 'cafeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'cafeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
